@echo off
echo Starting UCC Shuttle Tracker Server...
echo.
echo Killing any existing processes on port 3001...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3001') do (
    echo Killing process %%a...
    taskkill /f /pid %%a
)
echo.
echo Starting server on port 3001...
node server-enhanced.js
pause